# Copy this file to local.yml and modify to your liking
slack:
  domain: 'If you have ninjas.slack.com, then put ninjas here'

  # apiToken: This is not meant to be incoming/outgoing web hooks token, but the token you generate
  # on https://api.slack.com
  apiToken: 'InsertSlackAPITokenHere'
server:
  port: 8080
  useHttps: true
  sslPrivateKeyPath: '/path/to/privatekey.pem'
  sslCertificatePath: '/path/to/cert.pem'
ircServers:
  # set to false if you want self-signed SSL certs to be accepted by default
  # (you can also override this per server in db/db.json)
  rejectUnauthorizedTlsCerts: true
